Added required ( following ) files
shayan1234554321/Hello-microverse pull request #2
Opened 2023-01-10 22:01 UTC by shayan1234554321

- Updated READ.me file
- Added html file
- Added css file
- Added test.md file
- Added package-lock.json
- Addedpackage.json

2023-01-10 22:13 UTC, huseyinbiyik requested changes
Hi @shayan1234554321,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![Almost there](https://media.giphy.com/media/Rv6GGaNrRbtNConlYo/giphy.gif)

## Highlights
- Linter set up well and checks pass 🟢
- Github flow followed 👌
- .gitignore used to ignore requested files 📁

## Required Changes ♻️
-  Please make sure your commit messages are meaningful and descriptive for your next commits. Use imperative tense and capitalize the first word. For example, 
👌"Add logo to navigation bar"
👌"Fix close button functionality on mobile navbar"
❌ "Added logo to navigation bar"
❌ "Added HTML"

_Check the comments under the review._

## Optional suggestions
- [OPTIONAL] Please try to commit more often. It is important for keeping your project history and make action if you want to make changes to your project.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-10 22:13 UTC, huseyinbiyik commented on README.md
>  <a name="readme-top"></a>
- Kindly use [Microverse Readme template](https://github.com/microverseinc/readme-template) and make sure all the main sections present in yours and placeholders are replaced with your project and personal data. Only optional section is FAQ. Please remove the template logo on the top, if you have your own logo you can replace it with this one, otherwise please delete it. This is crucial to have a professional and instructive repository. 👌

2023-01-11 11:20 UTC, ABDULALI3468 requested changes
# Changes Required 👍 

Hi @shayan1234554321 , 

<img src="https://media3.giphy.com/media/31Q36EHJ7C5ZoIMw79/giphy.gif"/>

Great work on making the changes requested by a previous reviewer 👏 
You've done really really well implementing some of the requested changes, but there are still some which aren't been addressed yet.


 ## Highlights


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-11 11:20 UTC, ABDULALI3468 commented on README.md
>    <h3><b>Microverse README Template</b></h3>
Please consider removing the following line from README as it has nothing to do with your project. If you want to give credits to Microverse you can use the Acknowledgements section for this.

2023-01-11 11:20 UTC, ABDULALI3468 commented on README.md
> +SOFTWARE.
Kindly consider adding the following section to a separate file. You can name it as [LICENSE](https://github.com/ABDULALI3468/bookMe-frontend/blob/develop/LICENSE) and link that file in the README by using the following syntax:

`[Text like MIT in this case](link to the file)`

It will make your repository look more professional!

2023-01-11 11:46 UTC, shayan1234554321 commented on README.md
>    <h3><b>Microverse README Template</b></h3>
Should i remove from line 1 to line 10 ?? Which includes an a tag too

2023-01-11 11:48 UTC, shayan1234554321 commented on README.md
> +SOFTWARE.
How to link the file here? Example if there's a licence file in my project , will this be the correct text for that? [MIT] ( ./LICENSE)

2023-01-11 13:55 UTC, Shedrack-Sunday commented on README.md
> +SOFTWARE.
Hello @shayan1234554321 , yes! If the License file is at the root, you do it that way just as you pointed out 👍

2023-01-11 13:56 UTC, Shedrack-Sunday commented on README.md
>    <h3><b>Microverse README Template</b></h3>
Just leave the top tag, but remove the comments. it will make you =r code too bogus. 👍

2023-01-11 14:06 UTC, Shedrack-Sunday approved these changes
Hi @shayan1234554321  , 

Good job so far!

May I highlight the following:

- The repo looks professional.:heavy_check_mark:
- There are no linter errors:heavy_check_mark:
- You have descriptive PR:heavy_check_mark:

## STATUS: APPROVED :muscle::clap:

Congratulations! :tada:
Your project is complete!  It's time to merge it :shipit:
Great work on implementing the changes requested by the previous TSEs
 
 ## Optional suggestions
 
 - Please check the comment under the review.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread and tag me @algerina if something is not 100% clear.

2023-01-11 14:06 UTC, Shedrack-Sunday commented on README.md
> +- GitHub: [@githubhandle](https://github.com/shayan1234554321)
- [ Optional] Nice work here, but please add the remaining social links. Thats Twitter and Linkedin

2023-01-11 14:06 UTC, Shedrack-Sunday commented on README.md
> +No features
- [Optional] Alway delete an already made template such as in line `143` and add your custom own. 
- [Optional] Please always mention potential features. it shows a willingness to improve the project later on 👍

2023-01-11 14:20 UTC, merged